# Generated by Django 3.1.3 on 2020-11-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PbEncyclopedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('water', models.TextField(blank=True, null=True)),
                ('sun', models.TextField(blank=True, null=True)),
                ('propagation', models.TextField(blank=True, null=True)),
                ('hardiness', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pb_encyclopedia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.TextField(blank=True, null=True)),
                ('username', models.TextField(null=True)),
                ('password', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('USDA_zone', models.TextField(blank=True, null=True)),
                ('receive_water_notif', models.BooleanField(blank=True, null=True)),
                ('receive_repot_notif', models.BooleanField(blank=True, null=True)),
                ('receive_fertilizing_notif', models.BooleanField(blank=True, null=True)),
                ('notif_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
       migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.TextField(blank=True, null=True)),
                ('username', models.TextField(null=True)),
                ('password', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('USDA_zone', models.TextField(blank=True, null=True)),
                ('receive_water_notif', models.BooleanField(blank=True, null=True)),
                ('receive_repot_notif', models.BooleanField(blank=True, null=True)),
                ('receive_fertilizing_notif', models.BooleanField(blank=True, null=True)),
                ('notif_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
