# Generated by Django 3.1.3 on 2020-12-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201125_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprofile',
            name='nickname',
            field=models.TextField(blank=True, default='My Plant', null=True),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='photo',
            field=models.TextField(blank=True, default='https://i.imgur.com/4os1ZjY.png', null=True),
        ),
    ]
