# Generated by Django 3.1.3 on 2020-11-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_plantprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantprofile',
            options={},
        ),
    ]
