# Generated by Django 3.1.3 on 2020-12-02 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201201_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprofile',
            name='encyclopedia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pbencyclopedia'),
        ),
    ]
