# Generated by Django 3.1.3 on 2020-11-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201119_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='google_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
