# Generated by Django 3.1.3 on 2020-12-02 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201201_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprofile',
            name='encyclopedia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pbencyclopedia'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userprofile'),
        ),
    ]
