# Generated by Django 3.1.3 on 2020-12-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201201_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='receive_fertilizing_notif',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='receive_repot_notif',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='receive_water_notif',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
